users:
  progamrer: 672892838995820553
  hello: 650439182204010496
  jayd: 690265771955585029
  catvader: 816692546272100442
  fhd: 628672513345454122
  fhdbot: 963533621812158474
  
  groups:
    owner:
      - 672892838995820553
    dev:
      - 6504391822040104960
      - 672892838995820553
    staff:
      - 672892838995820553
      - 6504391822040104960
      - 690265771955585029
      - 816692546272100442
      - 628672513345454122
      - 845361227093508116
emojis:
  check_mark: âœ…
  warning: âš ï¸
  cross_mark: âŒ
  hourglass: âŒ›

  thumbs_up: 'ğŸ‘'
  clown: ğŸ¤¡

  arrow_right: 'â¡ï¸'
  arrow_left: 'â¬…ï¸'
  arrow_up: 'â¬†ï¸'
  arrow_down: 'â¬‡ï¸'
  vomiting_face: ğŸ¤®
  flushed: ğŸ˜³
  neutral: ğŸ˜
  raised_eyebrow: ğŸ¤¨
  blush: ğŸ˜Š
  heart_eyes: ğŸ˜
  heart_sparkle: ğŸ’–
  sparkle: âœ¨
  two_hearts: ğŸ’•
  twisted_arrows: ğŸ”€
  bar_full: '<:f:971070032241127536>'
  bar_half: '<:h:971070061139877939>'
  bar_empty: '<:e:971070086360215572>'
names:
  first:
    - Jason
    - Kyle
    - Joseph
    - Neng
    - Da
    - Jay
    - Shiva
    - Osama
    - Saddam
    - Hussein
    - Adolph
    - Joey
    - Nicholas
    - Alex
    - Dmitri
    - Vladimir
    - Zedong
    - Jihad
    - Bob
    - James
    - Carl
    - Raku
    - Canpooper
    - Shuva
    - Stalin
    - Kim Jong
    - Vladimir
    - Volodymyr
    - Bin Laden
    - Obama
    - Joe
    - Kimberly
    - Thomas
    - Johannes
    - Galileo
    - Luke
    - Yan
    - Washington
    - George
    - Ryan
    - Don
    - Donald
    - Riley
    - Google
    - Mia
    - Tony
    - Anthony
    - Aly
    - Alyson
    - Steven
    - Stephen
    - Benito
    - Tim
    - Jimmy
    - Nguyen
    - Abraham
    - Jesus
    - Mohammed
    - Muhammad
    - Jack
    - Jackson
    - COVID
  last:
    - Hitler
    - Mao
    - Kim
    - Hawking
    - Mardikar
    - Ghizali
    - Paolini
    - Massaquoi
    - Li
    - Zhao
    - Ping
    - Timers
    - Wood
    - Lester
    - Pablo
    - Putin
    - Lenin
    - Stalin
    - Mussolini
    - Mardikar
    - Sedjiu
    - Mackenzie
    - II of Poopland
    - I of Poopland
    - III of Poopland
    - IV of Poopland
    - V of Poopland
    - + ratio
    - ":joy_cat: :joy_cat: :joy_cat:"
  street_name_endings:
    - dale
    - glen
    - pass
    - brooke
    - pooper
    - raku
    - ""
    - ""
    - ""
  street_types:
    - Avenue
    - Street
    - Road
    - Drive
    - Pass
    - Plaza
    - Court
    - Circle
    - Boulevard
    - Freeway
    - Highway
    - Way
    - Pooper
